/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as IItemIdRouteImport } from './routes/i.$itemId'
import { Route as DSlugIndexRouteImport } from './routes/d.$slug.index'
import { Route as DSlugArchivedRouteImport } from './routes/d.$slug.archived'
import { Route as DSlugFavoritesRouteImport } from './routes/d.$slug.favorites'
import { Route as DSlugCCategoryRouteImport } from './routes/d.$slug.c.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IItemIdRoute = IItemIdRouteImport.update({
  id: '/i/$itemId',
  path: '/i/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugIndexRoute = DSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DSlugRoute,
} as any)
const DSlugArchivedRoute = DSlugArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => DSlugRoute,
} as any)
const DSlugFavoritesRoute = DSlugFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DSlugRoute,
} as any)
const DSlugCCategoryRoute = DSlugCCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => DSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/error': typeof AuthErrorRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/i/$itemId': typeof IItemIdRoute
  '/d/$slug/archived': typeof DSlugArchivedRoute
  '/d/$slug/favorites': typeof DSlugFavoritesRoute
  '/d/$slug/': typeof DSlugIndexRoute
  '/d/$slug/c/$category': typeof DSlugCCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/error': typeof AuthErrorRoute
  '/i/$itemId': typeof IItemIdRoute
  '/d/$slug/archived': typeof DSlugArchivedRoute
  '/d/$slug/favorites': typeof DSlugFavoritesRoute
  '/d/$slug': typeof DSlugIndexRoute
  '/d/$slug/c/$category': typeof DSlugCCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/error': typeof AuthErrorRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/i/$itemId': typeof IItemIdRoute
  '/d/$slug/archived': typeof DSlugArchivedRoute
  '/d/$slug/favorites': typeof DSlugFavoritesRoute
  '/d/$slug/': typeof DSlugIndexRoute
  '/d/$slug/c/$category': typeof DSlugCCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/auth/error'
    | '/d/$slug'
    | '/i/$itemId'
    | '/d/$slug/archived'
    | '/d/$slug/favorites'
    | '/d/$slug/'
    | '/d/$slug/c/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/auth/error'
    | '/i/$itemId'
    | '/d/$slug/archived'
    | '/d/$slug/favorites'
    | '/d/$slug'
    | '/d/$slug/c/$category'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/auth/error'
    | '/d/$slug'
    | '/i/$itemId'
    | '/d/$slug/archived'
    | '/d/$slug/favorites'
    | '/d/$slug/'
    | '/d/$slug/c/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  AuthErrorRoute: typeof AuthErrorRoute
  DSlugRoute: typeof DSlugRouteWithChildren
  IItemIdRoute: typeof IItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$itemId': {
      id: '/i/$itemId'
      path: '/i/$itemId'
      fullPath: '/i/$itemId'
      preLoaderRoute: typeof IItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug/': {
      id: '/d/$slug/'
      path: '/'
      fullPath: '/d/$slug/'
      preLoaderRoute: typeof DSlugIndexRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/d/$slug/archived': {
      id: '/d/$slug/archived'
      path: '/archived'
      fullPath: '/d/$slug/archived'
      preLoaderRoute: typeof DSlugArchivedRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/d/$slug/favorites': {
      id: '/d/$slug/favorites'
      path: '/favorites'
      fullPath: '/d/$slug/favorites'
      preLoaderRoute: typeof DSlugFavoritesRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/d/$slug/c/$category': {
      id: '/d/$slug/c/$category'
      path: '/c/$category'
      fullPath: '/d/$slug/c/$category'
      preLoaderRoute: typeof DSlugCCategoryRouteImport
      parentRoute: typeof DSlugRoute
    }
  }
}

interface DSlugRouteChildren {
  DSlugArchivedRoute: typeof DSlugArchivedRoute
  DSlugFavoritesRoute: typeof DSlugFavoritesRoute
  DSlugIndexRoute: typeof DSlugIndexRoute
  DSlugCCategoryRoute: typeof DSlugCCategoryRoute
}

const DSlugRouteChildren: DSlugRouteChildren = {
  DSlugArchivedRoute: DSlugArchivedRoute,
  DSlugFavoritesRoute: DSlugFavoritesRoute,
  DSlugIndexRoute: DSlugIndexRoute,
  DSlugCCategoryRoute: DSlugCCategoryRoute,
}

const DSlugRouteWithChildren = DSlugRoute._addFileChildren(DSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  AuthErrorRoute: AuthErrorRoute,
  DSlugRoute: DSlugRouteWithChildren,
  IItemIdRoute: IItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
